---
title: "Adult Mortality in the Metropolis of London 100–1850"
subtitle: "A Bayesian View from Osteological Data"
author: 
 - Nils Müller-Scheeßel^[Institute for Pre- and Proto History - Kiel University nils.mueller-scheessel@ufg.uni-kiel.de]
 - Katharina Fuchs^[Institute of Clinical Molecular Biology - Kiel University, k.fuchs@ikmb.uni-kiel.de]
 - Christoph Rinne^[Institute for Pre- and Proto History - Kiel University, crinne@ufg.uni-kiel.de]
date: "`r format(Sys.time(), '%d. %B %Y')`"
license: "CC-BY 4.0"
header-includes:
  #\renewcommand{\contentsname}{Inhalt}
  #\renewcommand{\figurename}{Abb.}
  #\renewcommand{\tablename}{Tab.}
papersize: a4
output:
  pdf_document:
    number_sections: true
    toc: true
    toc_depth: 2
    df_print: kable
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: true
#  html_notebook:
#        code_folding: hide
knit rmdfig_caption: true
urlcolor: blue
link-citations: true # make citations hyperlinks
linkcolor: blue
---

```{r knitr global options, include=FALSE}
# Global options for knitr
knitr::opts_chunk$set(echo=TRUE, fig.align="center")
```

# Chapter 03 Data

## Historical life tables

### Written sources, pre-processed

Preprocessing of data used in figure 6: Estimated modal ages.
Datasets are individualy preprocessed, s. ./liftables_preprocessed/ .
All data are refernced and aggregated in ./chapter_04_results/historical_lifetables.R

```{r }
source("./chapter_04_results/historical_lifetables.R")
kable(peers_ranges, caption = "English Peers (English_Peers.R")
kable(monks_ranges, caption = "Christ Church monks (Medieval_England.R")
kable(london_1728_1840_ranges, caption = "London population, range of age modes M (London_1728_1840.R)")
kable(london_1728_1840_ranges_r, caption = "London population, range of rate (London_1728_1840.R)")
kable(London_1841_ranges, caption = "London population (London_1841_raw_all.R)")
kable(eng_mort_ranges, caption = "English data (Wrigley et al. 1997) (English_Mortality.R)")
kable(HMD_UK_ranges, caption = "Human Mortality Database UK (HMD_UK.R)")
```